name: Deploy Contoso_University_Core
on:
 workflow_run:
  workflows: ["Pack Contoso_University_Core"]
  branches: [main]
  types:
    - completed
 workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
    # Display GH Default env vars 
      - name: Display GH Default env vars 
        run: |
         echo "github actor: ${{ secrets.USERNAME }}"
         echo "github actor: ${{ secrets.PASSWORD }}"
      # $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org1ebaf3ee.crm4.dynamics.com
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-file: contoso_university_core_managed.zip
